Repository Synergise-IIT-Bhubaneswar/Beta-Algo, pull requests merged in 2021-12, with the labels that each got.

#24 Added DFS and BFS algorithms of graph in Python
  python/graph/BFS_of_directed_graph.py
  python/graph/BFS_of_undirected_graph.py
  python/graph/DFS_of_directed_graph.py
  python/graph/DFS_of_undirected_graph.py
Labels: syn-accepted, syn-medium

#27 Rectified matrix_sort.py
  python/sort/matrix_sort.py
Labels: syn-beginner, syn-accepted

#35 Implemented DFS and BFS algorithms of graph in Java
  java/graph/BFS_directed_graph.java
  java/graph/BFS_undirected_graph.java
  java/graph/DFS_directed_graph.java
  java/graph/DFS_undirected_graph.java
Labels: syn-accepted, syn-easy

#30 Implemented dfs and bfs in c
  c/graph/bfs_for_directed_graph.c
  c/graph/bfs_for_undirected_graph.c
  c/graph/dfs_for_directed_graph.c
  c/graph/dfs_for_undirected_graph.c
Labels: syn-beginner, syn-accepted

#31 Implemented Warshall Algorithm in Java
  java/graph/warshall.java
Labels: syn-accepted, syn-easy
